language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox

deploy:
  provider: heroku
  api_key: "8c23e9d6-bfe3-4eb3-b22f-604d65f9dcb8"
